name: minio_flutter
description: minio client for dart based on minio-java-8.5.2.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.3 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.3
  import_sorter: ^4.6.0
  json_serializable: ^6.6.1
  lints: ^2.0.0
  path: ^1.8.3
  test: ^1.21.0
dependencies:
  collection: ^1.17.1
  convert: ^3.1.1
  crypto: ^3.0.2
  cryptography: ^2.4.0
  http: ^0.13.5
  intl: ^0.18.0
  json_annotation: ^4.8.0
  quiver: ^3.2.1
  time: ^2.1.3
  xml2json: ^5.3.6
